__version__ = "0.0.1"
"""Notion API wrapper for easy database one-to-many automation (cascade insert) in the form of logs"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto #0
__all__ = []

# %% ../nbs/index.ipynb #90c30996
__all__ = ['Database', 'TriggerDB', 'JunctionDB', 'LogDB', 'AutoLogger', 'NotionWebhook']

