__version__ = "0.0.1"
"""Notion API wrapper for easy database one-to-many automation"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/index.ipynb.

# %% auto #0
__all__ = ['notion', 'trigger', 'junction', 'log', 'db_logger', 'app', 'webhook']

# %% ../nbs/index.ipynb #90c30996
__all__ = ['Database', 'TriggerDB', 'JunctionDB', 'LogDB', 'AutoLogger', 'NotionWebhook']


# %% ../nbs/index.ipynb #a90a6a82
from notion_autolog.core import TriggerDB,JunctionDB,LogDB,AutoLogger
from notion_client import Client
import os

notion = Client(auth=os.getenv("NOTION_TOKEN"))

trigger = TriggerDB(os.getenv("PRODUCTION_PLAN_DB_ID"), notion, "Status", "Recipes", "Batches to make")
junction = JunctionDB(os.getenv("RECIPE_INGREDIENTS_DB_ID"), notion, "Recipes", "Ingredient Inventory", "Amount per batch")
log = LogDB(os.getenv("INGREDIENT_TRANSACTION_DB"), notion, "Ingredient", "Amount", "Production Plan", "Reason")
db_logger = AutoLogger(trigger, junction, log, "In Process", -1)

# %% ../nbs/index.ipynb #e7b12776
from fastapi import FastAPI,Request
from notion_autolog.webhook import NotionWebhook

app = FastAPI()

@app.post("/webhook")
async def webhook(request: Request):
    hook = NotionWebhook(await request.json())
    if hook.parent_db_id == os.getenv("PRODUCTION_PLAN_DB_ID"):
        if hook.type == 'page.created': return {"result": db_logger.process(hook.entity_id)}
    return {"status": "received"}
