"""Helper function for dealing with Notion Webhook"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_webhook.ipynb.

# %% auto #0
__all__ = ['NotionWebhook']

# %% ../nbs/01_webhook.ipynb #af93ad65
class NotionWebhook:
    """Handler for Notion webhook payloads.
    
    Attributes:
        data: The raw webhook payload data
        type: The type of webhook event
        entity_id: The ID of the entity that triggered the webhook
    """
    def __init__(self, data):
        """Initialize the webhook handler with payload data.
        
        Args:
            data: Dictionary containing the webhook payload from Notion
        """
        self.data = data
        self.type = data['type']
        self.entity_id = data['entity']['id']
    
    @property
    def parent_db_id(self):
        """Get the parent database ID with hyphens removed.
        
        Returns:
            String containing the parent database ID without hyphens, or empty string if not found
        """
        return self.data.get('data', {}).get('parent', {}).get('id', '').replace('-', '')
    
    @property
    def updated_props(self):
        """Get the list of properties that were updated in this webhook event.
        
        Returns:
            List of property names that were updated, or empty list if none
        """
        return self.data.get('data', {}).get('updated_properties', [])
